from fpdf import FPDF
from pathlib import Path

class PDFReportGenerator:
    def __init__(self, brand_name: str = "FinStock"):
        self.brand_name = brand_name

    def generate(self, symbol: str, stock_name: str, summary: str, level: str) -> Path:
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 24)
        pdf.set_text_color(21, 154, 156)  # FinStock Teal
        pdf.cell(0, 15, self.brand_name, ln=True, align="L")
        
        pdf.set_font("Arial", "B", 16)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, f"Stock Research Report: {stock_name} ({symbol})", ln=True)
        pdf.set_font("Arial", "I", 12)
        pdf.cell(0, 8, f"Expertise Level: {level.capitalize()}", ln=True)
        pdf.ln(5)
        
        # Summary Section
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "AI Investment Intelligence Summary", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(2)
        
        pdf.set_font("Arial", "", 11)
        # Using multi_cell for long text
        # Cleaning up markdown bold if present since FPDF doesn't parse it by default
        clean_summary = summary.replace("**", "").replace("__", "").replace("#", "")
        pdf.multi_cell(0, 7, clean_summary)
        
        pdf.ln(10)
        pdf.set_font("Arial", "I", 10)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(0, 10, f"Generated by {self.brand_name} AI Intelligence at {Path(__file__).resolve().name}", ln=True, align="C")
        
        # Save to temporary file
        output_path = Path(f"/tmp/{symbol}_{level}_report.pdf")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Handle Windows /tmp fallback
        if os.name == 'nt':
            output_path = Path(f"C:/temp/{symbol}_{level}_report.pdf")
            output_path.parent.mkdir(parents=True, exist_ok=True)

        pdf.output(str(output_path))
        return output_path

import os
